defaults:
  - launcher: local
  - solver: cem
  - _self_

world:
  env_name: swm/PushT-v1
  num_envs: ${eval.num_eval}
  max_episode_steps: ???

dataset:
  stats: ${eval.dataset_name}
  keys_to_cache:
    - action
    - proprio
    - state

seed: 42
policy: random
# Planning mode for FBLeWM:
#   official | forward | backward
#   fusion_avg05 | fusion_avg07 | fusion_max | fusion_min
#   switch_remain | switch_offset | meet
planning_mode: official

plan_config:
  horizon: 5
  receding_horizon: 5
  action_block: 5

eval:
  num_eval: 50
  goal_offset_steps: 25
  eval_budget: 50
  img_size: 224
  dataset_name: pusht_expert_train
  callables:
    - method: _set_state
      args:
        state:
          value: state
    - method: _set_goal_state
      args:
        goal_state:
          value: goal_state

output:
  filename: pusht_results.txt
